### PR TITLE
Fix strict mode compatibility

### LINKED ISSUE #1: lower option not supported?
Hi,

Thanks for the angular wrapper. I've noticed that the lowercase option isn't supported. {lower: true} Do you plan on adding this in?

### PR DESCRIPTION
**Pull request by mischah**
Hej, this awesome and tiny wrapper to slug was exactly what I was looking for.

But it doesn’t work with Angulars [strict-di mode](https://docs.angularjs.org/error/$injector/strictdi?p0=slugFilter).

This PR:
- Fixes compatibility with strict-di mode
- Updates dependencies 
  - Fixes #1 
- Bumps version in manifest files 
  - `bower.json` and `package.json`

So all you need to do is:
- merge 
- Tag release
- npm publish

:octocat:

### CODE REVIEW

**Comment by mischah** [comment]
P.S. Let me know if you want me to squash the commits 😊

**Comment by lucasconstantino** [comment]
Thanks a lot for the help on this. It's been a long time since I used this package. No need for squashing the commits; I even prefer this this way, I guess.

Ps.: I'll add you as a collaborator so that you can push new code directly if you wish ;)

**Comment by mischah** [comment]
Hej, thanks for merging and adding me.
Would you mind to add me as collaborator on npm as well? So I can publish the latest changes.

Just in case:
Add my username `mischah` over here: https://www.npmjs.com/package/angular-slug/access

**Comment by mischah** [comment]
Thanks. Just recognized on the [npm package page](https://www.npmjs.com/package/angular-slug)  that the latest version is still `0.0.3` and that I’m listed as collaborator.

So I just have published `0.0.4` 😂

**Pull request merged**
